orbs:
  react: thefrontside/react@0.2.0
  code-climate-quality: freighthub/code-climate-quality@0.0.4
version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:10.16.0
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            # when lock file changes, use increasingly general patterns to restore cache
            - yarn-packages-v1-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - yarn-packages-v1-{{ .Branch }}-
            - yarn-packages-v1-
      - run:
                name: Install Dependencies
                command: yarn install
      - save_cache:
          paths:
            - ~/.cache/yarn
          key: yarn-packages-v1-{{ .Branch }}-{{ checksum "yarn.lock" }}
      - run:
            name: Build Project
            command: yarn build
      - run:
            name: Run Tests
            command: yarn test
      - run:
            name: Setup Code Climate test-reporter
            command: |
              curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
              chmod +x ./cc-test-reporter
      - run:
            name: Test Coverage and send Coverage Report to Code Climate
            command: |
              ./cc-test-reporter before-build
              yarn run test:coverage
              ./cc-test-reporter after-build --debug -t lcov --exit-code $?
      - run:           
            name: Deploy to Firebase Hosting
            command: './node_modules/.bin/firebase deploy --token=$FIREBASE_TOKEN'